CREATE DATABASE IF NOT EXISTS USERDB;
USE USERDB;

-- ===========================
-- XÓA BẢNG THEO ĐÚNG THỨ TỰ
-- ===========================

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS MATCHES;
DROP TABLE IF EXISTS LOBBY_CHAT_HISTORY;
DROP TABLE IF EXISTS GLOBAL_CHAT_HISTORY;
DROP TABLE IF EXISTS ROOMS;
DROP TABLE IF EXISTS PLAYERS;

SET FOREIGN_KEY_CHECKS = 1;

-- ===========================
-- TABLE PLAYERS
-- ===========================

CREATE TABLE PLAYERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) UNIQUE,
    PHONE VARCHAR(20) UNIQUE,
    PASSWORDHASH VARCHAR(64) NOT NULL,
    SALT VARCHAR(50) NOT NULL,
    USER_LEVEL INT DEFAULT 1,
    XP INT DEFAULT 0,
    TOTAL_XP INT DEFAULT 0,
    LAST_LOGIN DATETIME,
    CREATED_AT DATETIME DEFAULT NOW()
);

-- ===========================
-- TABLE ROOMS
-- ===========================

CREATE TABLE ROOMS (
    ROOM_ID INT AUTO_INCREMENT PRIMARY KEY,
    ROOM_CODE VARCHAR(6) NOT NULL UNIQUE,
    ROOM_NAME VARCHAR(100) NOT NULL,
    ROOM_PASSWORD VARCHAR(100),

    PLAYER1_USERNAME VARCHAR(50),
    PLAYER2_USERNAME VARCHAR(50),

    ROOM_STATUS VARCHAR(20) DEFAULT 'WAITING',

    CREATED_AT DATETIME DEFAULT NOW(),
    LAST_ACTIVITY DATETIME DEFAULT NOW(),

    FOREIGN KEY (PLAYER1_USERNAME) REFERENCES PLAYERS(USERNAME) ON DELETE SET NULL,
    FOREIGN KEY (PLAYER2_USERNAME) REFERENCES PLAYERS(USERNAME) ON DELETE SET NULL
);

-- ===========================
-- GLOBAL CHAT
-- ===========================

CREATE TABLE GLOBAL_CHAT_HISTORY (
    MESSAGE_ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50),
    MESSAGE_TEXT TEXT NOT NULL,
    SENT_AT DATETIME DEFAULT NOW(),
    FOREIGN KEY (USERNAME) REFERENCES PLAYERS(USERNAME) ON DELETE SET NULL
);

CREATE INDEX IX_GLOBAL_CHAT_SENT_AT ON GLOBAL_CHAT_HISTORY(SENT_AT);
CREATE INDEX IX_GLOBAL_CHAT_USERNAME ON GLOBAL_CHAT_HISTORY(USERNAME);

-- ===========================
-- LOBBY CHAT
-- ===========================

CREATE TABLE LOBBY_CHAT_HISTORY (
    MESSAGE_ID INT AUTO_INCREMENT PRIMARY KEY,
    ROOM_CODE VARCHAR(6) NOT NULL,
    USERNAME VARCHAR(50),
    MESSAGE_TEXT TEXT NOT NULL,
    SENT_AT DATETIME DEFAULT NOW(),
    FOREIGN KEY (ROOM_CODE) REFERENCES ROOMS(ROOM_CODE) ON DELETE CASCADE,
    FOREIGN KEY (USERNAME) REFERENCES PLAYERS(USERNAME) ON DELETE SET NULL
);

CREATE INDEX IX_LOBBY_CHAT_ROOM_CODE ON LOBBY_CHAT_HISTORY(ROOM_CODE);
CREATE INDEX IX_LOBBY_CHAT_SENT_AT ON LOBBY_CHAT_HISTORY(SENT_AT);

-- ===========================
-- MATCHES
-- ===========================

CREATE TABLE MATCHES (
    MATCH_ID INT AUTO_INCREMENT PRIMARY KEY,
    ROOM_ID INT NOT NULL,
    WINNER_USERNAME VARCHAR(50),

    PLAYER1_WINS INT DEFAULT 0,
    PLAYER2_WINS INT DEFAULT 0,
    CURRENT_ROUND INT DEFAULT 1,
    TOTAL_ROUNDS INT DEFAULT 3,

    HEALTH_PLAYER1 INT DEFAULT 100,
    HEALTH_PLAYER2 INT DEFAULT 100,

    PLAYER1_MANA INT DEFAULT 0,
    PLAYER2_MANA INT DEFAULT 0,

    PARRY_COUNT INT DEFAULT 0,
    BLOCK_COUNT INT DEFAULT 0,
    SKILL_COUNT INT DEFAULT 0,

    PLAYER1_SCORE INT DEFAULT 0,
    PLAYER2_SCORE INT DEFAULT 0,
    MATCH_XP_PLAYER1 INT DEFAULT 0,
    MATCH_XP_PLAYER2 INT DEFAULT 0,

    MATCH_DURATION_SECONDS INT DEFAULT 0,
    CREATED_AT DATETIME DEFAULT NOW(),
    FINISHED_AT DATETIME,

    FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ROOM_ID) ON DELETE CASCADE,
    FOREIGN KEY (WINNER_USERNAME) REFERENCES PLAYERS(USERNAME) ON DELETE SET NULL
);

-- ===========================
-- TRIGGER UPDATE XP
-- ===========================

DROP TRIGGER IF EXISTS TRG_UPDATE_TOTAL_XP;
DELIMITER //

CREATE TRIGGER TRG_UPDATE_TOTAL_XP
AFTER INSERT ON MATCHES
FOR EACH ROW
BEGIN
    UPDATE PLAYERS P
    SET P.TOTAL_XP = P.TOTAL_XP + NEW.MATCH_XP_PLAYER1,
        P.XP = P.XP + NEW.MATCH_XP_PLAYER1
    WHERE P.USERNAME = (SELECT PLAYER1_USERNAME FROM ROOMS WHERE ROOM_ID = NEW.ROOM_ID);

    UPDATE PLAYERS P
    SET P.TOTAL_XP = P.TOTAL_XP + NEW.MATCH_XP_PLAYER2,
        P.XP = P.XP + NEW.MATCH_XP_PLAYER2
    WHERE P.USERNAME = (SELECT PLAYER2_USERNAME FROM ROOMS WHERE ROOM_ID = NEW.ROOM_ID);
END//

DELIMITER ;

-- ===========================
-- STORED PROCEDURES
-- ===========================

DROP PROCEDURE IF EXISTS SP_CHECK_ROOM_CODE_EXISTS;
DELIMITER //

CREATE PROCEDURE SP_CHECK_ROOM_CODE_EXISTS(IN RoomCode VARCHAR(6))
BEGIN
    SELECT EXISTS(SELECT 1 FROM ROOMS WHERE ROOM_CODE = RoomCode) AS `Exists`;
END//

DELIMITER ;

DROP PROCEDURE IF EXISTS SP_CREATE_ROOM_EMPTY;
DELIMITER //

CREATE PROCEDURE SP_CREATE_ROOM_EMPTY(
    IN RoomCode VARCHAR(6),
    IN RoomName VARCHAR(100),
    IN RoomPassword VARCHAR(100)
)
BEGIN
    IF EXISTS (SELECT 1 FROM ROOMS WHERE ROOM_CODE = RoomCode) THEN
        SELECT 0 AS Success, 'Room code exists' AS Message, NULL AS RoomId;
    ELSE
        INSERT INTO ROOMS(ROOM_CODE, ROOM_NAME, ROOM_PASSWORD)
        VALUES (RoomCode, RoomName, RoomPassword);
        SELECT 1 AS Success, 'Room created' AS Message, LAST_INSERT_ID() AS RoomId;
    END IF;
END//

DELIMITER ;

DROP PROCEDURE IF EXISTS SP_JOIN_ROOM;
DELIMITER //

CREATE PROCEDURE SP_JOIN_ROOM(
    IN RoomCode VARCHAR(6),
    IN Pwd VARCHAR(100),
    IN Username VARCHAR(50)
)
label_join: BEGIN
    DECLARE P1 VARCHAR(50);
    DECLARE P2 VARCHAR(50);
    DECLARE RP VARCHAR(100);

    SELECT PLAYER1_USERNAME, PLAYER2_USERNAME, ROOM_PASSWORD
    INTO P1, P2, RP
    FROM ROOMS WHERE ROOM_CODE = RoomCode;

    IF RP IS NOT NULL AND RP <> Pwd THEN
        SELECT 0 AS Success, 'Wrong password' AS Message;
        LEAVE label_join;
    END IF;

    IF P1 IS NULL THEN
        UPDATE ROOMS SET PLAYER1_USERNAME = Username WHERE ROOM_CODE = RoomCode;
    ELSEIF P2 IS NULL THEN
        UPDATE ROOMS SET PLAYER2_USERNAME = Username, ROOM_STATUS='READY'
        WHERE ROOM_CODE = RoomCode;
    ELSE
        SELECT 0 AS Success, 'Room full' AS Message;
        LEAVE label_join;
    END IF;

    SELECT 1 AS Success, 'Joined room' AS Message;
END//

DELIMITER ;

DROP PROCEDURE IF EXISTS SP_LEAVE_ROOM;
DELIMITER //

CREATE PROCEDURE SP_LEAVE_ROOM(
    IN RoomCode VARCHAR(6),
    IN Username VARCHAR(50)
)
BEGIN
    UPDATE ROOMS
    SET 
        PLAYER1_USERNAME = IF(PLAYER1_USERNAME = Username, NULL, PLAYER1_USERNAME),
        PLAYER2_USERNAME = IF(PLAYER2_USERNAME = Username, NULL, PLAYER2_USERNAME),
        ROOM_STATUS = 'WAITING'
    WHERE ROOM_CODE = RoomCode;

    SELECT 1 AS Success, 'Left room' AS Message;
END//

DELIMITER ;