CREATE DATABASE USERDB;
GO

USE USERDB;
GO

CREATE TABLE PLAYERS
(
ID INT IDENTITY(1,1) PRIMARY KEY,
USERNAME NVARCHAR(50) NOT NULL UNIQUE,
EMAIL NVARCHAR(100) NULL UNIQUE,
PHONE NVARCHAR(20) NULL UNIQUE,
PASSWORDHASH NVARCHAR(64) NOT NULL,
SALT NVARCHAR(50) NOT NULL,
USER_LEVEL INT DEFAULT 1,
XP INT DEFAULT 0,
TOTAL_XP INT DEFAULT 0,
CHARACTER_USED NVARCHAR(50) NULL,
LAST_LOGIN DATETIME NULL,
CREATED_AT DATETIME DEFAULT GETDATE()
)

CREATE TABLE CHARACTERS
(
CHARACTER_NAME NVARCHAR(50) PRIMARY KEY,
HP INT NOT NULL,
DAMAGE INT NOT NULL,
SPEED INT NOT NULL,
STAMINA INT NOT NULL,
MANA INT NOT NULL,
SKILL_DESCRIPTION NVARCHAR(255) NULL,
CREATED_AT DATETIME DEFAULT GETDATE() 
)

CREATE TABLE ROOMS
(
ROOM_ID INT IDENTITY(1,1) PRIMARY KEY,
ROOM_NAME NVARCHAR(100) NOT NULL,
ROOM_PASSWORD NVARCHAR(100),
PLAYER1_USERNAME NVARCHAR(50),
PLAYER2_USERNAME NVARCHAR(50),
PLAYER1_CHARACTER NVARCHAR(50),
PLAYER2_CHARACTER NVARCHAR(50),
ROOM_STATUS NVARCHAR(20) DEFAULT 'WAITING',
CREATED_AT DATETIME DEFAULT GETDATE(),
FOREIGN KEY (PLAYER1_USERNAME) REFERENCES PLAYERS(USERNAME),
FOREIGN KEY (PLAYER2_USERNAME) REFERENCES PLAYERS(USERNAME),
FOREIGN KEY (PLAYER1_CHARACTER) REFERENCES CHARACTERS(CHARACTER_NAME),
FOREIGN KEY (PLAYER2_CHARACTER) REFERENCES CHARACTERS(CHARACTER_NAME)
)

CREATE TABLE MATCHES
(
MATCH_ID INT IDENTITY(1,1) PRIMARY KEY,
ROOM_ID INT NOT NULL,
WINNER INT NULL,
PLAYER1_WINS INT DEFAULT 0,
PLAYER2_WINS INT DEFAULT 0,
CURRENT_ROUND INT DEFAULT 1,
HEALTH_PLAYER1 INT,
HEALTH_PLAYER2 INT,
PLAYER1_MANA INT DEFAULT 0,
PLAYER2_MANA INT DEFAULT 0,
PARRY_COUNT INT DEFAULT 0,
BLOCK_COUNT INT DEFAULT 0,
SKILL_COUNT INT DEFAULT 0,
PLAYER1_SCORE INT DEFAULT 0,
PLAYER2_SCORE INT DEFAULT 0,
MATCH_XP_PLAYER1 INT DEFAULT 0,
MATCH_XP_PLAYER2 INT DEFAULT 0,
CREATED_AT DATETIME DEFAULT GETDATE(),
FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ROOM_ID),
FOREIGN KEY (WINNER) REFERENCES PLAYERS(ID)
)
GO

CREATE TRIGGER TRG_UPDATE_TOTAL_XP
ON MATCHES
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;

    -- UPDATE TOTAL_XP CHO PLAYER 1
    UPDATE P
    SET P.TOTAL_XP = P.TOTAL_XP + I.MATCH_XP_PLAYER1
    FROM PLAYERS P
    INNER JOIN INSERTED I ON 1 = 1
    INNER JOIN ROOMS R ON R.ROOM_ID = I.ROOM_ID
    WHERE P.USERNAME = R.PLAYER1_USERNAME;

    -- UPDATE TOTAL_XP CHO PLAYER 2
    UPDATE P
    SET P.TOTAL_XP = P.TOTAL_XP + I.MATCH_XP_PLAYER2
    FROM PLAYERS P
    INNER JOIN INSERTED I ON 1 = 1
    INNER JOIN ROOMS R ON R.ROOM_ID = I.ROOM_ID
    WHERE P.USERNAME = R.PLAYER2_USERNAME;
END;
GO

